-- Seed FAQ, Warranty, and Awards pages
-- Run after seed_site_pages.sql (or anytime — uses ON CONFLICT)

INSERT INTO site_pages (slug, meta_title, meta_description, content) VALUES
('faq', 'FAQ', 'Answers to common questions about building a custom home with John Buchan Homes on the Seattle Eastside.',
'{"hero":{"eyebrow":"Questions","title":"What to","title_emphasis":"expect."},"intro":"Building a custom home is a significant investment of time and trust. Here are answers to the questions we hear most often from Eastside homeowners.","categories":[{"title":"Getting Started","items":[{"question":"Do you only build on my lot?","answer":"Yes. We specialize in ground-up custom homes and major remodels on the Seattle Eastside — Bellevue, Clyde Hill, Medina, Redmond, and surrounding communities."},{"question":"How do I know if my lot is buildable?","answer":"We evaluate your lot early in the process — zoning, setbacks, slope, utilities, and access."},{"question":"Can I bring my own architect?","answer":"Absolutely. We also offer in-house design and architecture if you prefer a single team from concept through construction."}]},{"title":"Process & Timeline","items":[{"question":"How long does a custom build take?","answer":"Most custom homes on the Eastside take 12–18 months from breaking ground to final walkthrough, depending on size, complexity, and permitting."},{"question":"Will I have a single point of contact?","answer":"Yes. Our Client Concierge stays with you from first conversation through aftercare."}]},{"title":"Budget & Pricing","items":[{"question":"How is pricing structured?","answer":"We provide transparent estimates before breaking ground so there are no surprises when construction begins."},{"question":"Do you offer a cost estimator?","answer":"Yes. Use our online Build Estimator for a preliminary sense of budget, then contact us to refine numbers."}]},{"title":"After Move-In","items":[{"question":"What warranty do you provide?","answer":"We stand behind our work with a structured warranty and responsive aftercare. See our Warranty & Aftercare page for full details."}]}],"cta_title":"Still have questions?"}'::jsonb),

('warranty', 'Warranty & Aftercare', 'John Buchan Homes warranty coverage and ongoing aftercare for custom homes on the Seattle Eastside.',
'{"hero":{"eyebrow":"Peace of Mind","title":"Warranty &","title_emphasis":"Aftercare."},"intro":"Our relationship does not end at the walkthrough. For generations, Buchan clients have counted on us long after the keys are handed over.","sections":[{"title":"Built to last — backed by us.","body":"Every Buchan home is constructed to a standard we would build for our own families."},{"title":"Your concierge, after move-in.","body":"Mischelle McCall and our team remain your single point of contact for warranty questions and guidance."}],"coverage_items":[{"title":"Structural warranty","description":"Coverage for major structural components per our written warranty agreement."},{"title":"Workmanship","description":"We address defects in materials and workmanship reported during the warranty period promptly."},{"title":"Punch list & close-out","description":"Before you move in, we walk every room with you. Open items are tracked to completion."},{"title":"Ongoing support","description":"Questions after warranty? We are still here. Buchan clients are part of a community we have served for over 65 years."}],"cta_title":"Questions about coverage?"}'::jsonb),

('awards', 'Awards, Press & Credentials', 'Recognition, press, and professional credentials for John Buchan Homes — Bellevue custom builder since 1960.',
'{"hero":{"eyebrow":"Recognition","title":"Awards &","title_emphasis":"credentials."},"intro":"For more than six decades, John Buchan Homes has been recognized by clients, industry peers, and the design community for craftsmanship, service, and integrity on the Seattle Eastside.","awards":[{"title":"Best of Houzz — Design","year":"2022","description":"Recognized for excellence in residential design and client satisfaction."},{"title":"Best of Houzz — Design","year":"2021","description":"Honored for outstanding design work and portfolio quality."},{"title":"Best of Houzz — Service","year":"2020","description":"Awarded for exceptional client service throughout the building process."},{"title":"Best of Houzz — Service","year":"2017","description":"Consistent recognition for communication, reliability, and results."},{"title":"Best of Houzz — Service","year":"2016","description":"Client-reviewed excellence in custom home building."},{"title":"Best of Houzz — Service","year":"2014","description":"Among the first Eastside builders honored on Houzz for service."},{"title":"Houzz Community Recommended","year":"—","description":"Recommended by the Houzz community for quality and professionalism."},{"title":"25K+ Houzz Saves","year":"—","description":"Our work has been saved and shared by thousands of homeowners and design professionals."}],"press":[{"title":"Built for the rain","source":"John Buchan Homes Blog","date":"2026","excerpt":"What built for the rain really means in the Pacific Northwest.","url":"/blog/built-for-the-rain"},{"title":"Clyde Hill estate, framing to finish","source":"John Buchan Homes Blog","date":"2026","excerpt":"A look at every stage of one of our most considered builds to date.","url":"/blog/clyde-hill-framing-to-finish"}],"credentials":[{"title":"Licensed & insured","body":"John Buchan Homes is a licensed general contractor serving Bellevue and the greater Seattle Eastside."},{"title":"65 years in business","body":"Three generations of Buchan craftsmen — building on the Eastside since 1960."},{"title":"Design-build expertise","body":"In-house architecture and interiors, unified under one roof from first sketch to final walkthrough."},{"title":"Client concierge","body":"Dedicated single point of contact throughout your project and beyond."}],"cta_title":"Experience the Buchan standard."}'::jsonb)

ON CONFLICT (slug) DO UPDATE SET
  meta_title = EXCLUDED.meta_title,
  meta_description = EXCLUDED.meta_description,
  content = EXCLUDED.content,
  updated_at = now();
