-- Seed site pages with current marketing content
-- Run after 002_site_pages.sql

INSERT INTO site_pages (slug, meta_title, meta_description, content) VALUES
('home', 'Bellevue''s Custom Home Builder', 'Built on your lot. Designed for your life. Custom homes on the Seattle Eastside since 1960.',
'{"hero":{"eyebrow":"Celebrating 65 Years · Est. 1960","title":"Bellevue''s Custom","title_emphasis":"Home Builder","subtitle":"Built on your lot. Designed for your life.","image_url":"/assets/ph-arch-1.png","marquee":"Since 1960 · Bellevue · Clyde Hill · Medina · Redmond · Custom Build · Design · Remodel ·","cta_primary_url":"https://estimator.buchan.com/","cta_primary_label":"Get Your Build Estimate"},"legacy":{"title":"65 years.","title_line2":"One standard.","title_emphasis":"Yours.","eyebrow":"The Buchan Legacy","paragraphs":["Since 1960, three generations of Buchan craftsmen have built on the Seattle Eastside — in Bellevue, Clyde Hill, Medina, and Redmond. We don''t build to a spec sheet. We build to a standard, and that standard is yours.","Every joint, every grain, every quiet wall is a decision made by hand. The result is a home that feels inevitable — as if it could have stood nowhere else."]},"services":{"eyebrow":"What We Do","title":"Three ways to build","title_emphasis":"something lasting.","items":[{"title":"Build","description":"Ground-up custom homes on your lot.","image_url":"/assets/ph-arch-2.png","link":"/build"},{"title":"Design","description":"Architecture and interiors, unified.","image_url":"/assets/ph-arch-3.png","link":"/design"},{"title":"Remodel","description":"Transform the home you already love.","image_url":"/assets/ph-arch-4.png","link":"/remodel"}]},"recent_work":{"eyebrow":"Recent Work","title":"Homes we''re proud of."},"concierge":{"eyebrow":"The Concierge Promise","quote":"Every client deserves a single point of contact who knows their project inside and out. That''s the Buchan way.","cite":"Mischelle McCall · Client Concierge","image_url":"/assets/ph-arch-1.png"}}'::jsonb),

('about', 'About Us', 'Three generations of Buchan craftsmen building on the Seattle Eastside since 1960.',
'{"hero":{"eyebrow":"Our Story","title":"Built on legacy.","title_emphasis":"Defined by you."},"timeline":{"eyebrow":"Timeline","title":"65 years of craft.","items":[{"year":"1960","title":"Founded","body":"John Buchan opens his first workshop in Bellevue."},{"year":"1985","title":"Second Generation","body":"David Buchan joins the family business."},{"year":"2014","title":"Design Studio","body":"In-house architecture and interiors launched."},{"year":"Today","title":"65 Years","body":"Three generations, one standard — yours."}]},"mission":{"eyebrow":"Our Mission","title":"Your standard is","title_emphasis":"our standard.","body":"We don''t build to impress other builders. We build to the standard you set — in every joint, every finish, every quiet detail.","image_url":"/assets/ph-arch-2.png"},"team":{"eyebrow":"The Team","title":"People who care","title_emphasis":"deeply.","members":[{"name":"Mischelle McCall","role":"Client Concierge","image_url":"/assets/ph-arch-1.png"},{"name":"David Buchan","role":"President","image_url":"/assets/ph-arch-1.png"},{"name":"Sarah Lindqvist","role":"Design Director","image_url":"/assets/ph-arch-1.png"},{"name":"Marcus Reyes","role":"Construction Manager","image_url":"/assets/ph-arch-1.png"}]},"giving_back":{"eyebrow":"Giving Back","title":"Building community,","title_emphasis":"not just homes.","image_url":"/assets/ph-arch-3.png"},"cta":{"join_title":"Join our team.","join_body":"We''re always looking for craftspeople who share our standard.","land_title":"We buy land.","land_body":"Have a lot on the Eastside? We''d love to hear about it."}}'::jsonb),

('services', 'Services', 'Build, Design, and Remodel — three ways to create something lasting with John Buchan Homes.',
'{"hero":{"eyebrow":"What We Do","title":"Three ways to build","title_emphasis":"something lasting."},"items":[{"title":"Build","slug":"build","description":"Ground-up custom homes on your lot — from foundation to final walkthrough.","image_url":"/assets/ph-arch-2.png"},{"title":"Design","slug":"design","description":"Architecture and interiors under one roof, designed for how you live.","image_url":"/assets/ph-arch-3.png"},{"title":"Remodel","slug":"remodel","description":"Whole-home and room-scale renovations with the same Buchan standard.","image_url":"/assets/ph-arch-4.png"}],"cta_title":"Ready to begin?"}'::jsonb),

('build', 'Custom Build', 'Ground-up custom homes on your lot in Bellevue, Clyde Hill, Medina, and Redmond.',
'{"hero":{"eyebrow":"Services","title":"Custom","title_emphasis":"Build"},"image_url":"/assets/ph-arch-1.png","steps":[{"n":"01","title":"Lot & Vision","body":"We evaluate your land and understand your goals."},{"n":"02","title":"Design","body":"Architecture and interiors developed together."},{"n":"03","title":"Estimate","body":"Transparent pricing before we break ground."},{"n":"04","title":"Permitting","body":"We navigate codes and approvals on your behalf."},{"n":"05","title":"Build","body":"Craftsmanship at every stage, on your lot."}],"cta_title":"Let''s talk about your project."}'::jsonb),

('design', 'Design', 'Architecture and interior design unified under one roof.',
'{"hero":{"eyebrow":"Services","title":"Design &","title_emphasis":"Architecture"},"image_url":"/assets/ph-arch-3.png","steps":[{"n":"01","title":"Discovery","body":"How you live, how you want to feel at home."},{"n":"02","title":"Concept","body":"Initial plans and material palettes."},{"n":"03","title":"Development","body":"Detailed drawings and specifications."},{"n":"04","title":"Build","body":"Design intent carried through construction."}],"cta_title":"Let''s talk about your project."}'::jsonb),

('remodel', 'Remodel', 'Whole-home and room-scale renovations on the Seattle Eastside.',
'{"hero":{"eyebrow":"Services","title":"Thoughtful","title_emphasis":"Remodel"},"image_url":"/assets/ph-arch-4.png","steps":[{"n":"01","title":"Assessment","body":"Understanding your existing home and goals."},{"n":"02","title":"Design","body":"Plans that respect what works and improve what doesn''t."},{"n":"03","title":"Phasing","body":"Minimal disruption while you stay in your home."},{"n":"04","title":"Finish","body":"The same Buchan standard, in the home you already love."}],"cta_title":"Let''s talk about your project."}'::jsonb),

('process', 'Our Process', 'From first conversation to final walkthrough — how we build custom homes on the Eastside.',
'{"hero":{"eyebrow":"How We Work","title":"The Buchan","title_emphasis":"Process"},"steps":[{"n":"01","title":"Conversation & Lot","duration":"Week 1–2","body":"We listen first — your vision, your land, your timeline.","tag":"Discovery"},{"n":"02","title":"Design Development","duration":"Weeks 3–12","body":"Architecture and interiors evolve together under one roof.","tag":"Design"},{"n":"03","title":"Estimate & Contract","duration":"Week 13–14","body":"Transparent pricing. No surprises before we break ground.","tag":"Planning"},{"n":"04","title":"Permitting","duration":"Weeks 15–20","body":"We navigate codes and approvals on your behalf.","tag":"Permits"},{"n":"05","title":"Construction","duration":"Months 6–18","body":"Craftsmanship at every stage, with regular site visits.","tag":"Build"},{"n":"06","title":"Warranty & Aftercare","duration":"Ongoing","body":"Our relationship doesn''t end at the walkthrough.","tag":"Care"}],"cta_title":"Ready to begin?"}'::jsonb),

('neighborhoods', 'Neighborhoods', 'Custom homes in Bellevue, Clyde Hill, Medina, Redmond, and across the Seattle Eastside.',
'{"hero":{"eyebrow":"Where We Build","title":"Eastside","title_emphasis":"Neighborhoods"},"areas":[{"name":"Bellevue","body":"From Bridle Trails to downtown, we know every neighborhood.","image_url":"/assets/ph-arch-1.png"},{"name":"Clyde Hill","body":"Estate-scale homes on some of the Eastside''s most coveted lots.","image_url":"/assets/ph-arch-2.png"},{"name":"Medina","body":"Lake Washington views and quiet streets — built to match.","image_url":"/assets/ph-arch-3.png"},{"name":"Redmond","body":"Growing families and established neighborhoods we''ve served for decades.","image_url":"/assets/ph-arch-4.png"}],"cta_title":"Find your neighborhood."}'::jsonb),

('testimonials', 'Testimonials', 'What our clients say about building with John Buchan Homes.',
'{"hero":{"eyebrow":"Client Stories","title":"In their","title_emphasis":"words."},"featured":{"quote":"Building with Buchan felt like working with family — patient, precise, and deeply committed to getting it right.","cite":"The Harmon Family · Clyde Hill","image_url":"/assets/ph-arch-1.png"},"quotes":[{"name":"The Castellanos Family","city":"Clyde Hill","quote":"They treated our home like it was their own — every detail considered, every question answered."},{"name":"James & Elena Park","city":"Medina","quote":"The process was transparent from day one. No surprises, just craftsmanship."},{"name":"Robert Whitmore","city":"Bellevue","quote":"Three generations of builders who still show up on site. That matters."},{"name":"Sarah Lindqvist","city":"Hunts Point","quote":"Our remodel exceeded what we imagined — and felt inevitable when it was done."},{"name":"David Okonkwo","city":"Redmond","quote":"Built on our lot, on our timeline, to our standard. Exactly as promised."},{"name":"Priya Anand","city":"Yarrow Point","quote":"Mischelle made sure we never felt lost in the process. That concierge touch is real."}],"cta_title":"Ready to write your story?"}'::jsonb),

('contact', 'Contact', 'Get in touch with John Buchan Homes — custom builder on the Seattle Eastside since 1960.',
'{"hero":{"eyebrow":"Get in Touch","title":"Start the","title_emphasis":"conversation."},"inquiry_title":"Send an inquiry","service_options":["I want to build a custom home","I am looking for a new home","I have land to sell","I''m planning a remodel","General inquiry"],"visit_title":"Visit us","phone":"425.827.2266","phone_href":"tel:4258272266","office":"Bellevue, Washington\nServing the Seattle Eastside","cta_title":"Know your numbers?"}'::jsonb)

ON CONFLICT (slug) DO NOTHING;

-- Mark first 3 demo properties as featured (if seed properties exist)
UPDATE properties SET featured = true, featured_order = 1 WHERE slug = 'clyde-hill-estate';
UPDATE properties SET featured = true, featured_order = 2 WHERE slug = 'medina-modern';
UPDATE properties SET featured = true, featured_order = 3 WHERE slug = 'bridle-trails-retreat';
